Neos:
  Contribute:
    gitHub:
      contributer:
        accessToken:
      origin:
        organization: Neos-GitHub-Test
      repositories:
        flow:
          origin: Flow
          contributer: Flow