Neos:
  Contribute:
    gitHub:
      origin:
        organization: 'neos'
        repositories:
          flow:
            name: 'flow-development-collection'
            packageDirectory: 'Framework'
          neos:
            name: 'neos-development-collection'
            packageDirectory: 'Neos'
      contributor:
        accessToken:
        repositories:
          flow:
            name:
          neos:
            name: