Neos:
  Contribute:
    gitHub:
      origin:
        organization: 'Neos-GitHub-Test'
        repositories:
          flow: 'Flow'
          neos: 'Neos'
      contributer:
        accessToken:
        repositories:
          flow:
          neos: