Neos:
  Contribute:
    gitHub:
      origin:
        organization: 'kitsunet'
        repositories:
          flow:
            name: 'Flow'
            packageDirectory: 'Framework'
          neos:
            name: 'Neos'
            packageDirectory: 'Neos'
      contributor:
        accessToken:
        repositories:
          flow:
            name:
          neos:
            name: